### ISSUE TITLE
How is it to be working?

### ISSUE THREAD

**Issue by RahmanM** [gfrancischelli/servicenow-uploader-webpack-plugin#2]
Hi,
I created the app as per https://medium.com/@pishchulin/react-application-in-servicenow-8bdbb1e69c0c and created the config file and other changes as per your page e.g. including my SNow URL and password stuff, but when build is complete nothing happened.

What is this plugin supposed to be doing? Saving a record into sys_ui_script?

I didn't get any error or anything but nothing was updated either.

Do you have any detailed docs or a video will be appreciated!

many thanks

**Comment by gfrancischelli** [comment]
Hi @RahmanM !

This nice tutorial teaches how to use react in servicenow using `create-react-app`, whose webpack compilation result produces multiple files (not supported *yet*).

I'm aiming to [support multiple files](#1) in the next release, then it will be compatible with `create-react-app`.

Any help is welcome 😄 !

Have you tried the basic example from the [README](https://github.com/gfrancischelli/servicenow-uploader-webpack-plugin/blob/master/README.md) ?

**Comment by RahmanM** [comment]
Great news!
Looking forward to the next release to support multiple files. 
Thanks!
